name: CI/CD Pipeline for LLaMA Server

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  # Configure for Docker Hub
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/llama-server

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker Hub login using secrets
      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Extract metadata for the Docker image
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=sha,prefix=sha-,format=short

      # Build and push Docker image
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true  # Disable cache to avoid previous issues

      # Install kubectl and kind
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Install Kind
        uses: helm/kind-action@v1.8.0
        with:
          install_only: true

      - name: Create Kind cluster
        run: |
          chmod +x ./scripts/setup-kind.sh
          ./scripts/setup-kind.sh

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.3'

      # Add Helm repos
      - name: Add Helm repositories
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      # Deploy minimal monitoring stack with simplified values
      - name: Deploy monitoring
        run: |
          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
          
          # Create simplified values for Prometheus
          cat > monitoring/prometheus-values-ci.yaml << EOF
          alertmanager:
            enabled: false
            
          kubeStateMetrics:
            enabled: false
            
          nodeExporter:
            enabled: false
            
          prometheusOperator:
            admissionWebhooks:
              enabled: false
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 50m
                memory: 64Mi
                
          prometheus:
            enabled: true
            service:
              type: NodePort
              nodePort: 30900
            prometheusSpec:
              retention: 1h
              resources:
                limits:
                  cpu: 250m
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
                  
          grafana:
            enabled: true
            adminPassword: "admin"
            service:
              type: NodePort
              nodePort: 30300
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 50m
                memory: 64Mi
          EOF
          
          # Try installation with retries
          for i in {1..3}; do
            echo "Attempt $i to install Prometheus..."
            if helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
              --namespace monitoring \
              --values monitoring/prometheus-values-ci.yaml \
              --timeout 5m; then
              echo "Prometheus installed successfully"
              break
            else
              echo "Prometheus installation attempt $i failed, retrying..."
              # Clean up potential failed resources
              kubectl -n monitoring delete service,deployment,statefulset,configmap,pod,secret --all --grace-period=0 --force || true
              if [ $i -eq 3 ]; then
                echo "Warning: Prometheus installation failed after 3 attempts, continuing with deployment anyway"
              fi
              # Wait before retrying
              sleep 30
            fi
          done

      # Fetch built image to Kind - FIXED for both pull request and push scenarios
      - name: Load Docker image to Kind
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # For PRs, build locally without pushing
            echo "Building local image for pull request..."
            docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/llama-server:pr-${{ github.event.pull_request.number }} .
            kind load docker-image ${{ secrets.DOCKER_HUB_USERNAME }}/llama-server:pr-${{ github.event.pull_request.number }} --name llama-cluster
            echo "IMAGE_TAG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            # For pushes, pull the pushed image using the first tag
            echo "Getting tags from metadata action..."
            TAGS_JSON='${{ steps.meta.outputs.json }}'
            FIRST_TAG=$(echo $TAGS_JSON | jq -r '.tags[0]')
            echo "First tag: $FIRST_TAG"
            
            if [ -z "$FIRST_TAG" ] || [ "$FIRST_TAG" = "null" ]; then
              # Fallback to building locally if no tag is available
              echo "No tags found, building locally..."
              docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/llama-server:sha-${{ github.sha }} .
              IMAGE_TAG="sha-${{ github.sha }}"
            else
              echo "Pulling image: $FIRST_TAG"
              docker pull $FIRST_TAG
              # Extract just the tag portion from the full image reference
              IMAGE_TAG=$(echo "$FIRST_TAG" | cut -d ':' -f 2)
              echo "Extracted tag: $IMAGE_TAG"
            fi
            
            kind load docker-image ${{ secrets.DOCKER_HUB_USERNAME }}/llama-server:$IMAGE_TAG --name llama-cluster
            echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          fi

      # Deploy app using Helm
      - name: Deploy LLaMA server with Helm
        run: |
          kubectl create namespace llama --dry-run=client -o yaml | kubectl apply -f -
          
          # Show the image tag being used
          echo "Using image: ${{ secrets.DOCKER_HUB_USERNAME }}/llama-server:${{ env.IMAGE_TAG }}"
          
          helm upgrade --install llama-server ./helm/llama-server \
            --namespace llama \
            --set image.repository=${{ secrets.DOCKER_HUB_USERNAME }}/llama-server \
            --set image.tag=${{ env.IMAGE_TAG }} \
            --set image.pullPolicy=IfNotPresent \
            --timeout 10m

      # Verify deployment with extended wait time
      - name: Verify deployment
        run: |
          echo "Waiting for LLaMA server to be ready..."
          kubectl -n llama rollout status deployment/llama-server --timeout=10m
          echo "LLaMA server is ready"
          echo "Services available:"
          kubectl -n llama get svc
          
      - name: Get service URLs
        run: |
          echo "LLaMA Server is available at: http://localhost:30080"
          echo "Metrics endpoint is available at: http://localhost:30090/metrics"
          echo "Prometheus UI is available at: http://localhost:30900"
          echo "Grafana is available at: http://localhost:30300 (admin/admin)"